### ISSUE TITLE
-sp (--samepath)  switch does not put previews in the correct folder when working recursively

### ISSUE THREAD

**Issue by kulkatt** [Tetrax-10/batch-preview-generator#2]
say I have a folder AA under folder A, and the video files are all in AA.
if I use A as input path, then all previews will be put in A instead of AA

**Comment by Tetrax-10** [comment]
It's not a bug; that's how I made it. But it should work as you described. I don't know why I didn't implement it that way. I will fix that soon. Thanks.

**Comment by Tetrax-10** [comment]
Fixed it 6561497, check out [version v1.2](https://github.com/Tetrax-10/batch-preview-generator/releases/tag/v1.2)
