### ISSUE TITLE
F-String errors and FFMPEG aspect ratio if width is not divisible by 2

### ISSUE THREAD

**Issue by viper86it** [Tetrax-10/batch-preview-generator#3]
Hi,
thank you for your work! It's exactly what I'm looking for.
Anyway I spent a bit of time to get it working, your code has a lot of errors with f-string syntax.

I've corrected all strings is commander.py, preview.py and ffmpeg.py. Please check attached files. Now works well with python 3.10.12

In ffmpeg.py, in function generate_preview_chunck(), it was an error related to file width calculation. Using "-1" is calculated keeping aspect ratio, but if width is not divisible by 2 ffmpeg returns an error.

To solve it I changed:
`-vf {scale}=-1:{args.resolution}{video}`
to
`-vf "{scale}=-2:{args.resolution}{video}"`

as explained here:
https://trac.ffmpeg.org/wiki/Scaling

I hope this will help you:
[Fix.zip](https://github.com/user-attachments/files/17374256/Fix.zip)

**Comment by Tetrax-10** [comment]
Can you make a PR instead of attaching a zip file?
